# Generated by Django 3.2.3 on 2021-05-18 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qresponse',
            name='respondent_email',
        ),
        migrations.CreateModel(
            name='QuestionnaireRespondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
            ],
            options={
                'unique_together': {('questionnaire', 'respondent_email')},
            },
        ),
        migrations.AddField(
            model_name='qresponse',
            name='questionnaire_respondent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnairerespondent'),
            preserve_default=False,
        ),
    ]
