# Generated by Django 3.2.3 on 2021-05-18 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20210518_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.question'),
        ),
        migrations.AlterField(
            model_name='qresponse',
            name='questionnaire_respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent', to='questionnaire.questionnairerespondent'),
        ),
        migrations.AlterField(
            model_name='questionnairerespondent',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent', to='questionnaire.questionnaire'),
        ),
    ]
