# Generated by Django 3.2.3 on 2021-05-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20210518_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairerespondent',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaire.questionnaire'),
        ),
    ]
